server:
  port: 8071

logging:
  level:
    com.tananushka.resource.svc: DEBUG
    root: INFO

spring:
  application:
    name: "resource-svc"
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:5432/resource_svc_db"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect
svc:
  song:
    instance: "SONG-SVC"
    songs-endpoint: "/songs"

eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}"