server:
  port: 8072

logging:
  level:
    com.tananushka.song.svc: DEBUG
    root: INFO

spring:
  application:
    name: song-svc
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:5432/song_svc_db"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}"